### ISSUE TITLE
Error: unexpected keyword argument 'method_whitelist'

### ISSUE THREAD

**Issue by swvanderlaan** [hyunhwan-jeong/bear-app-to-notion#6]
Tried to run the code, but got this. 

```
python script.py
Traceback (most recent call last):
  File "/Users/username/git/bear-app-to-notion/script.py", line 12, in <module>
    client = NotionClient(token_v2=token_v2)
  File "/Users/username/miniconda3/lib/python3.9/site-packages/notion/client.py", line 77, in __init__
    self.session = create_session(client_specified_retry)
  File "/Users/username/miniconda3/lib/python3.9/site-packages/notion/client.py", line 39, in create_session
    retry = Retry(
TypeError: __init__() got an unexpected keyword argument 'method_whitelist'
```

First, issue though is that it is pretty hard to find the cookie.  See attached screenshot, is it this?
![Screenshot 2023-09-06 at 11 54 47](https://github.com/hyunhwan-jeong/bear-app-to-notion/assets/8877879/b840c3e5-90e4-491a-86fc-d5b3403c7709)

Also, I am on python 3.9, is this an issue?

**Comment by shorttompkins** [comment]
fwiw I got the same error.  I noticed in the `token_v2` value it actually starts with `v03%3` so Im wondering if they made some updates on the Notion side that this script needs to be updated to support. 🤷
